CREATE TABLE Contacts(
	contId NUMBER(4) PRIMARY KEY,
	firstName VARCHAR(15) NOT NULL,
	midName VARCHAR(15) NOT NULL,
	lastName VARCHAR(15) NOT NULL,
	gender VARCHAR(10) NOT NULL,
	mobileNUMBER1 VARCHAR(11) NOT NULL UNIQUE,
	mobileNUMBER2 VARCHAR(11) NOT NULL UNIQUE,
	officialEmail VARCHAR(30) NOT NULL UNIQUE,
	homeEmail VARCHAR(30) NOT NULL UNIQUE,
	category VARCHAR(10) NOT NULL,
	Organization VARCHAR(15) NOT NULL,
	Designation VARCHAR(20) NOT NULL
);

CREATE SEQUENCE contIdSeq
START WITH 1
INCREMENT BY 1;
